version: "2"
services:
  app: #app will have code in it. links to db
    build: .
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    command: --local-infile=1
